export const LEER_CONTACTOS = "LEER_CONTACTOS";
export const AGREGAR_CONTACTOS = "AGREGAR_CONTACTOS";
export const EDITAR_CONTACTOS = "EDITAR_CONTACTOS";
export const ELIMINAR_CONTACTOS = "ELIMINAR_CONTACTOS";
